# Redis configuration file
bind 0.0.0.0
protected-mode no
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no

# Persistence
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Max memory config
maxmemory 256mb
maxmemory-policy allkeys-lru
